---
fixtures:
  repositories:
    common: "git://github.com/simp/pupmod-simp-common"
    iptables: "git://github.com/simp/pupmod-simp-iptables"
    network: "git://github.com/simp/pupmod-simp-network"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
  symlinks:
    gfs2: "#{source_dir}"
